trainer:
  devices: 1
  accelerator: auto
  epoch_count: 10
  stopping_patience: 5

model:
  huggingface:
    huggingface_model: t5-small
    huggingface_nnet: T5ForConditionalGeneration
    huggingface_tokenizer: T5Tokenizer
    text_tokenizer_max_len: 512
    kw_tokenizer_max_len: 32
    nnet:
      _target_: transformers.${model.huggingface.huggingface_nnet}.from_pretrained
      pretrained_model_name_or_path: ${model.huggingface.huggingface_model}
    tokenizer:
      _target_: transformers.${model.huggingface.huggingface_tokenizer}.from_pretrained
      pretrained_model_name_or_path: ${model.huggingface.huggingface_model}
  optimizer:
    _target_: torch.optim.Adam
    lr: 0.001
  loss:
    _target_: src.losses.CrossEntropy
  output_max_len: 32
  test_output: /net/tscratch/people/plgmstroinski/logs/outputs/

data:
  path: /net/tscratch/people/plgmstroinski/data/standard
  num_workers: 8
  batch_size: 64

logging:
  wandb:
    project: athena-test
    local_path: /net/tscratch/people/plgmstroinski/logs
  lightning:
    local_path: /net/tscratch/people/plgmstroinski/logs