defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  
  - override hydra/output: null

trainer:
  devices: 1
  accelerator: auto
  epoch_count: 10
  stopping_patience: 5

model:
  huggingface:
    huggingface_model: t5-small
    huggingface_nnet: T5ForConditionalGeneration
    huggingface_tokenizer: T5Tokenizer
    text_tokenizer_max_len: 512
    kw_tokenizer_max_len: 32
    nnet:
      _target_: transformers.${model.huggingface.huggingface_nnet}.from_pretrained
      pretrained_model_name_or_path: ${model.huggingface.huggingface_model}
    tokenizer:
      _target_: transformers.${model.huggingface.huggingface_tokenizer}.from_pretrained
      pretrained_model_name_or_path: ${model.huggingface.huggingface_model}
  optimizer:
    _target_: torch.optim.Adam
    lr: 0.001
  scheduler:
    _target_:torch.optim.lr_scheduler.ExponentialLR
    gamma: 0.1
  loss:
    _target_: src.losses.CrossEntropy
  output_max_len: 32
  test_output: ./

data:
  path: data/experiments/standard
  num_workers: 8
  batch_size: 64

logging:
  wandb:
    project: my-test-project 
    local_path: ./
  lightning:
    local_path: ./
